[email]
imap_host = "outlook.office365.com"
imap_username = "yay@uw.edu"
imap_password = "bibabopababibo"
imap_port = 993
imap_ssl = true

[reg]
cw = "abcdefgxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx123456"
quarter = 1
year = 2024
netid = "yay"
password = "bibabopababibo"

[sections]
[sections.cse414]
section_sln = 13009
lecture_sln = 13005
[sections.cse333]
section_sln = 12941
lecture_sln = 12938