[email]
imap_host = "outlook.office365.com"
imap_username = "yay@uw.edu"
imap_password = "bibabopababibo"
imap_port = 993
imap_ssl = true

[reg]
cw = "abcdefgxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx123456"
quarter = 1
year = 2024
netid = "yay"
password = "bibabopababibo"